-- ============================================================
-- 뷰티워크 · target_companies 홈페이지/인스타 URL 채우기 (웹 확인분 151개)
-- 인스타만 있는 곳은 인스타 주소로. 확인 안 된 곳은 비워둠(관리자 페이지 ✎로 추가).
-- 멱등: 홈페이지가 비어있는 행만 갱신. Supabase SQL Editor에서 실행.
-- ============================================================
UPDATE target_companies t SET homepage = v.url
FROM (VALUES
  ('헤어샵', '리안헤어 (RIAHN)', 'https://riahn.co.kr'),
  ('헤어샵', '에이바헤어 (AVAHIR)', 'https://www.avahair.co.kr'),
  ('헤어샵', '준오헤어 (JUNO HAIR)', 'https://www.junohair.com'),
  ('헤어샵', '박승철헤어스투디오', 'https://www.pschair.co.kr'),
  ('헤어샵', '로이드밤 (LLOYD BOMB)', 'https://lloydbomb.com'),
  ('헤어샵', '이철헤어커커', 'https://www.leechulhairkerker.co.kr/'),
  ('헤어샵', '모즈토리 (구 토리헤어)', 'https://toryhair.com'),
  ('헤어샵', '이가자헤어비스', 'https://leekaja.co.kr'),
  ('헤어샵', '아이디헤어 (id hair)', 'https://idhair.co.kr'),
  ('헤어샵', '박준뷰티랩', 'https://www.parkjun.com'),
  ('헤어샵', '제오헤어 (XEO HAIR)', 'http://www.xeohair.com'),
  ('헤어샵', '블루클럽 (Blue Club)', 'https://www.blueclub.co.kr'),
  ('헤어샵', '나이스가이', 'http://www.iniceguy.com'),
  ('헤어샵', '리챠드프로헤어', 'https://www.leechstyle.com'),
  ('헤어샵', '지노헤어', 'https://www.instagram.com/xinohair_official/'),
  ('헤어샵', '권홍헤어', 'https://kwonhonghair.com'),
  ('헤어샵', '차홍아르더 / 차홍룸', 'https://chahongsalon.com'),
  ('헤어샵', '순수 (SUNSOO)', 'https://soonsoobeauty.com'),
  ('헤어샵', '제니하우스 (JENNYHOUSE)', 'http://www.jennyhouse.co.kr'),
  ('헤어샵', '이훈헤어칼라', 'http://www.2hoon.co.kr'),
  ('헤어샵', '아이앤투헤어', 'https://www.instagram.com/in2haircoiffure/'),
  ('헤어샵', '라뷰티코아 (La Beauty Core)', 'https://www.rabeautycore.com'),
  ('헤어샵', '포레스타 (Foresta)', 'https://www.instagram.com/foresta.black/'),
  ('메이크업', '정샘물 플롭스 (JUNGSAEMMOOL)', 'https://www.jsmbeauty.com'),
  ('메이크업', '김활란뮤제네프', 'http://museeneuf.co.kr'),
  ('메이크업', '차홍아르더 (CHAHONG ARDOR)', 'https://chahongsalon.com'),
  ('메이크업', '순수 (SUNSOO)', 'https://soonsoobeauty.com'),
  ('메이크업', '조성아뷰티 / 아티스트 레이블', 'https://chosungahbeauty.com'),
  ('메이크업', '제니하우스 (청담힐 / 프리모)', 'https://www.jennyhouse.co.kr'),
  ('메이크업', '위위아뜰리에 by 서옥 (OuiOui)', 'https://www.instagram.com/ouioui_kr'),
  ('메이크업', '에이바이봄 (A. by BOM)', 'https://www.instagram.com/abybom__official'),
  ('메이크업', '알루 (ALUU 청담점/도산점)', 'https://aluu.co.kr'),
  ('메이크업', '밈 (MIMM)', 'https://www.instagram.com/mimm_official'),
  ('메이크업', '조이187 (JOY187)', 'https://www.instagram.com/joy187.official'),
  ('메이크업', '애브뉴준오 (Avenue JUNO)', 'https://www.junohair.com/avenuejuno'),
  ('메이크업', '이엘 (EL 헤어메이크업)', 'https://www.instagram.com/elhairmakeup'),
  ('메이크업', '보보리스 (VOVORIS)', 'https://www.instagram.com/boboris_salon'),
  ('메이크업', '빗앤붓 (Bit & Boot)', 'https://www.instagram.com/bit.boot'),
  ('메이크업', '겐그레아 (GENGREA)', 'https://www.instagram.com/cenchrea_official'),
  ('메이크업', '살롱드뮤사이 (Salon de Musai)', 'http://musai.co.kr'),
  ('메이크업', '컬처앤네이처 (Culture & Nature)', 'https://www.cultureandnature.kr'),
  ('메이크업', '헤움 (HEUM)', 'https://www.instagram.com/heumm.official/'),
  ('메이크업', '라뷰티코아 (La Beauty Core)', 'https://www.rabeautycore.com'),
  ('메이크업', '보이드바이박철 (Void by Parkchul)', 'https://voidbyparkchul.com'),
  ('메이크업', '스타일플로어 (Style Floor)', 'https://www.stylefloor.co.kr'),
  ('메이크업', '라메종뷰티 (La Maison)', 'https://www.instagram.com/lamaison_beauty/'),
  ('메이크업', '포레스타 (Foresta)', 'https://www.instagram.com/foresta.black/'),
  ('메이크업', '살롱바다', 'https://www.instagram.com/salonbaadaa'),
  ('메이크업', '롤링제이 (Rolling J)', 'https://www.instagram.com/rollingjay_official/'),
  ('메이크업', '샤인수 (Shine Soo)', 'https://www.shinesoo.co.kr'),
  ('메이크업', '코코리아 메이크업', 'https://www.instagram.com/cocoreamakeup/'),
  ('네일&속눈썹', '포쉬네일 (Forsythe Nail)', 'https://forsynail.com'),
  ('네일&속눈썹', '네일몰 (Nailmall) 연계 샵', 'https://www.nailmall.net'),
  ('네일&속눈썹', '골든네일 (Golden Nail)', 'https://www.instagram.com/goldennail_company/'),
  ('네일&속눈썹', '제니하우스 네일', 'https://www.jennyhouse.co.kr'),
  ('네일&속눈썹', '위위아뜰리에 네일', 'https://www.instagram.com/ouioui_kr/'),
  ('네일&속눈썹', '애브뉴준오 네일', 'https://www.junohair.com'),
  ('네일&속눈썹', '알루 (ALUU) 네일', 'https://aluu.co.kr'),
  ('네일&속눈썹', '차홍아르더 네일/뷰티', 'https://chahongsalon.com'),
  ('네일&속눈썹', '정샘물 플롭스 네일', 'https://www.jsmbeauty.com'),
  ('네일&속눈썹', '조이187 네일', 'https://www.instagram.com/joy187.official/'),
  ('네일&속눈썹', '김활란뮤제네프 네일', 'http://museeneuf.co.kr'),
  ('스킨&바디케어', '약손명가 (Yakson)', 'https://yaksonhouse.com'),
  ('스킨&바디케어', '끌리메 (CCLIME)', 'https://cclime.co.kr'),
  ('스킨&바디케어', '얼짱몸짱', 'http://www.beaupeople.com'),
  ('스킨&바디케어', '달리아스파 (Dahlia Spa)', 'https://dalia.kr'),
  ('스킨&바디케어', '위뷰티 (WEBEAUTY)', 'https://www.webeauty.co.kr'),
  ('스킨&바디케어', '더 트리니티 스파', 'https://www.trinityspa.co.kr'),
  ('스킨&바디케어', '스파에이르 (SPA EIR)', 'http://spaeir.co.kr'),
  ('스킨&바디케어', '설화수 스파 (Sulwhasoo Spa)', 'https://www.sulwhasoo.com'),
  ('스킨&바디케어', 'SPA 1899 (구 정관장 스파G)', 'https://spa1899.co.kr'),
  ('스킨&바디케어', '여용국 (Yeoyongguk)', 'https://yeoyongguk.com'),
  ('스킨&바디케어', '스파 드 엘르 (Spa de ELLE)', 'https://spa-the-el.com'),
  ('스킨&바디케어', '반얀트리 스파 (Banyan Tree)', 'https://www.banyantreeclub.com'),
  ('스킨&바디케어', '차움 테라스파 (Chaum)', 'https://www.chaum.net'),
  ('두피&탈모', '닥터스칼프 (Dr.Scalp)', 'https://www.drscalp.com'),
  ('두피&탈모', 'WT메소드 (WT-Method)', 'https://wt-methode.co.kr'),
  ('두피&탈모', '웰킨 두피탈모센터 (Wellkin)', 'https://www.wellkin.co.kr'),
  ('두피&탈모', '아미치0.3 (Amichi0.3)', 'https://www.amici.co.kr'),
  ('두피&탈모', '탑스칼프 (Top Scalp)', 'http://www.topscalp.com'),
  ('두피&탈모', '이문원 모발한의원/헤어랩', 'https://leemoonwon.com'),
  ('두피&탈모', '더모락 (The Morak)', 'https://www.themorak.com'),
  ('두피&탈모', '자올 닥터스파 (Zaol)', 'https://thezaol.com'),
  ('두피&탈모', '모제림 스칼프케어', 'https://www.mojelim.com'),
  ('두피&탈모', '맥스웰 피부과 두피센터', 'https://www.maxwellhair.co.kr'),
  ('두피&탈모', '포헤어 모발이식 센터', 'https://www.forhair.co.kr'),
  ('두피&탈모', '리더스 피부과 두피케어', 'https://www.beautyleader.co.kr'),
  ('두피&탈모', '오라클 두피센터', 'http://www.oracleclinic.com'),
  ('두피&탈모', '임이석테마 피부과 두피', 'https://www.beautyskin.kr'),
  ('두피&탈모', '차움 뷰티라이프 두피스파', 'https://www.chaum.net'),
  ('두피&탈모', '앙포레 헤드스파 (Enforet)', 'http://enforet.com'),
  ('두피&탈모', '케라스타즈 럭셔리 스파', 'https://www.kerastase.co.kr'),
  ('두피&탈모', '아베다 헤드스파 (Aveda)', 'https://www.avedakorea.com'),
  ('두피&탈모', '준오헤어 에코 헤드스파', 'https://www.junohair.com'),
  ('두피&탈모', '헤드스파 K (HeadSpa K)', 'https://headspak.com'),
  ('리테일&커머스', 'CJ올리브영 (OLIVE YOUNG)', 'https://www.oliveyoung.co.kr'),
  ('리테일&커머스', '시코르 (CHICOR)', 'https://chicor.com'),
  ('리테일&커머스', '세포라 코리아 (SEPHORA)', 'https://www.sephora.kr'),
  ('리테일&커머스', '아리따움 (ARITAUM)', 'https://www.aritaum.com'),
  ('리테일&커머스', '네이처컬렉션 (Nature Collection)', 'https://www.naturecollection.com'),
  ('리테일&커머스', '롯데온 뷰티 (On-And-Beauty)', 'https://www.lotteon.com'),
  ('리테일&커머스', 'SSG.COM 뷰티 (먼데이 뷰티)', 'https://www.ssg.com'),
  ('리테일&커머스', '현대H몰 뷰티 (H-Beauty)', 'https://www.hyundaihmall.com'),
  ('리테일&커머스', '온누리약국 뷰티 / 웰니스', 'https://www.onnuristore.com'),
  ('리테일&커머스', '롭스 플러스 (LOHB''s+)', 'https://www.lotteon.com'),
  ('리테일&커머스', '갤러리아 뷰티몰', 'https://www.galleria.co.kr'),
  ('리테일&커머스', 'AK몰 뷰티관', 'https://www.akmall.com'),
  ('리테일&커머스', '시코르닷컴 (CHICOR.com)', 'https://chicor.com'),
  ('리테일&커머스', '이마트 뷰티존', 'https://emart.ssg.com'),
  ('리테일&커머스', '홈플러스 뷰티 코너', 'https://www.homeplus.co.kr'),
  ('리테일&커머스', '뷰티컬리 (Beauty Kurly)', 'https://www.kurly.com'),
  ('리테일&커머스', '무신사 뷰티 (MUSINSA Beauty)', 'https://www.musinsa.com'),
  ('리테일&커머스', '지그재그 뷰티 (ZIGZAG)', 'https://zigzag.kr'),
  ('리테일&커머스', '에이블리 뷰티 (ABLY)', 'https://a-bly.com'),
  ('리테일&커머스', '29CM 뷰티', 'https://www.29cm.co.kr'),
  ('리테일&커머스', 'W컨셉 뷰티 (W CONCEPT)', 'https://www.wconcept.co.kr'),
  ('리테일&커머스', '쿠팡 R.LUX (알럭스)', 'https://rlux.coupang.com'),
  ('리테일&커머스', '쿠팡 뷰티 (Coupang Beauty)', 'https://www.coupang.com'),
  ('리테일&커머스', '네이버 쇼핑 뷰티윈도', 'https://shopping.naver.com'),
  ('리테일&커머스', '카카오톡 선물하기 (뷰티관)', 'https://gift.kakao.com'),
  ('리테일&커머스', '11번가 뷰티 (OOO뷰티)', 'https://www.11st.co.kr'),
  ('리테일&커머스', 'G마켓 / 옥션 뷰티관', 'https://www.gmarket.co.kr'),
  ('리테일&커머스', '위메프 뷰티', 'https://www.wemakeprice.com'),
  ('리테일&커머스', '티몬 뷰티', 'https://www.tmon.co.kr'),
  ('리테일&커머스', 'GS SHOP 뷰티', 'https://www.gsshop.com'),
  ('리테일&커머스', 'CJ온스타일 뷰티', 'https://www.cjonstyle.com'),
  ('리테일&커머스', '롯데홈쇼핑 뷰티 (L.CLUB)', 'https://www.lotteimall.com'),
  ('리테일&커머스', 'NS홈쇼핑 뷰티관', 'https://www.nsmall.com'),
  ('리테일&커머스', 'SK스토아 뷰티', 'https://www.skstoa.com'),
  ('리테일&커머스', '에이피알 D2C (메디큐브/에이프릴)', 'https://themedicube.co.kr'),
  ('리테일&커머스', '아모레몰 (Amore Mall)', 'https://www.amoremall.com'),
  ('리테일&커머스', '클럽클리오 (Club Clio)', 'https://clubclio.co.kr'),
  ('리테일&커머스', '마녀공장 공식몰', 'https://manyo.co.kr'),
  ('리테일&커머스', 'VT 코스메틱 자사몰', 'https://vt-cosmetics.com'),
  ('리테일&커머스', '가히 (KAHI) 공식몰', 'https://kahicosmetics.co.kr'),
  ('리테일&커머스', '달바 (d''Alba) 공식몰', 'https://dalba.co.kr'),
  ('리테일&커머스', '조선미녀 (Beauty of Joseon)', 'https://beautyofjoseon.com'),
  ('리테일&커머스', '아누아 (ANUA) 공식몰', 'https://anua.kr'),
  ('리테일&커머스', '스킨1004 (SKIN1004)', 'https://skin1004korea.com'),
  ('리테일&커머스', '롬앤 (rom&nd) 자사몰', 'https://romand.co.kr'),
  ('리테일&커머스', '코스알엑스 (COSRX) 몰', 'https://www.cosrx.com'),
  ('리테일&커머스', '라운드랩 (Round Lab)', 'https://roundlab.co.kr'),
  ('리테일&커머스', '토니모리 공식몰 (TMONEYMOLY)', 'https://www.tonymoly.co.kr'),
  ('리테일&커머스', '스킨푸드 공식몰', 'https://www.theskinfood.com'),
  ('리테일&커머스', '이니스프리 공식몰', 'https://www.innisfree.com'),
  ('리테일&커머스', '에뛰드 공식몰', 'https://www.etude.com'),
  ('리테일&커머스', '미샤 공식몰 (ABLE SHOP)', 'https://www.beautynet.co.kr'),
  ('리테일&커머스', '바닐라코 (BANILA CO)', 'https://www.banilaco.com'),
  ('리테일&커머스', '투쿨포스쿨 공식몰', 'https://www.toocoolforschool.com'),
  ('리테일&커머스', '헤라 (HERA) 브랜드관', 'https://www.hera.com'),
  ('리테일&커머스', '설화수 (Sulwhasoo) 몰', 'https://www.sulwhasoo.com')
) AS v(group_name, brand_name, url)
WHERE t.group_name = v.group_name AND t.brand_name = v.brand_name
  AND (t.homepage IS NULL OR t.homepage = '');
