export const INSIGHTS = [
  { id: 1, category: "트렌드", title: "2025 뷰티 업계를 뒤흔들 10가지 트렌드", desc: "K-뷰티의 글로벌 확장, 클린뷰티, AI 피부 분석까지. 올해 뷰티 업계를 이끌 핵심 키워드를 정리했습니다.", date: "2025.01.20", readTime: "5분", color: "#f3e8f7", emoji: "✨", featured: true },
  { id: 2, category: "커리어", title: "뷰티 MD가 되기 위한 5가지 필수 역량", desc: "현직 시니어 MD가 알려주는 진짜 실전 노하우. 포트폴리오 구성부터 면접 팁까지.", date: "2025.01.17", readTime: "7분", color: "#e8f0fe", emoji: "💼", featured: true },
  { id: 3, category: "연봉정보", title: "뷰티 업계 직무별 연봉 리포트 2025", desc: "마케팅, MD, 디자인, SCM 등 주요 직무별 연봉 데이터를 공개합니다.", date: "2025.01.15", readTime: "10분", color: "#e8f5e9", emoji: "📊", featured: true },
  { id: 4, category: "브랜드스토리", title: "아누아(ANUA)는 어떻게 틱톡에서 글로벌 브랜드가 됐나", desc: "스킨케어 브랜드 아누아의 틱톡샵 성공 전략.", date: "2025.01.12", readTime: "8분", color: "#fff3e0", emoji: "🌿", featured: false },
  { id: 5, category: "취업팁", title: "뷰티 회사 면접, 이것만 알면 합격한다", desc: "뷰티 업계 인사담당자가 직접 알려주는 면접 준비 가이드.", date: "2025.01.10", readTime: "6분", color: "#fce4ec", emoji: "🎯", featured: false },
  { id: 6, category: "트렌드", title: "클린뷰티 시대, 화장품 성분 분석가의 역할이 커진다", desc: "소비자 성분 인식이 높아지면서 새롭게 주목받는 직무.", date: "2025.01.08", readTime: "5분", color: "#e8eaf6", emoji: "🔬", featured: false },
  { id: 7, category: "커리어", title: "해외 뷰티 브랜드 취업, 어떻게 준비하나", desc: "로레알, 에스티로더 등 글로벌 뷰티 기업 취업을 위한 실전 준비 가이드.", date: "2025.01.05", readTime: "9분", color: "#f1f8e9", emoji: "🌍", featured: false },
  { id: 8, category: "연봉정보", title: "경력 5년차 뷰티 마케터 연봉 협상 성공 사례", desc: "연봉 협상에 성공한 뷰티 마케터의 실제 경험담.", date: "2025.01.03", readTime: "7분", color: "#fff8e1", emoji: "💰", featured: false },
  { id: 9, category: "브랜드스토리", title: "달바(d'Alba)의 글로벌 성공 비결: SCM 전략", desc: "한국 중소 뷰티 브랜드가 유럽 시장을 공략한 공급망 관리 전략 분석.", date: "2024.12.30", readTime: "6분", color: "#e0f2f1", emoji: "🏆", featured: false },
  { id: 10, category: "취업팁", title: "포트폴리오 없이 뷰티 MD 신입으로 취업하는 법", desc: "스펙보다 중요한 것들. 실무 경험 없이도 합격한 사람들의 공통점.", date: "2024.12.27", readTime: "8분", color: "#e8f0fe", emoji: "📝", featured: false },
  { id: 11, category: "트렌드", title: "2025 K-뷰티 수출 트렌드: 동남아 vs 북미", desc: "K-뷰티의 글로벌 확장이 가속화되는 가운데, 지역별 전략 차이점 분석.", date: "2024.12.24", readTime: "7분", color: "#f3e8f7", emoji: "🌏", featured: false },
  { id: 12, category: "커리어", title: "뷰티 업계 이직, 몇 년차에 하는 게 좋을까?", desc: "데이터로 보는 뷰티 업계 이직 최적 타이밍과 연봉 상승 전략.", date: "2024.12.20", readTime: "6분", color: "#fff3e0", emoji: "🔄", featured: false },
  { id: 13, category: "브랜드스토리", title: "조선미녀, 아마존에서 K-뷰티 1위가 된 비결", desc: "전통 한방 브랜드가 북미 Z세대를 사로잡은 마케팅 전략.", date: "2024.12.17", readTime: "9분", color: "#fce4ec", emoji: "🏮", featured: false },
  { id: 14, category: "연봉정보", title: "뷰티 업계 vs 일반 소비재: 연봉 비교 분석", desc: "같은 직무라도 업종에 따라 연봉이 다른 이유. 현직자 데이터 공개.", date: "2024.12.14", readTime: "5분", color: "#e8f5e9", emoji: "💹", featured: false },
  { id: 15, category: "취업팁", title: "뷰티 회사 자기소개서, 이렇게 쓰면 떨어진다", desc: "수백 개의 자소서를 검토한 인사담당자가 알려주는 실수 TOP 10.", date: "2024.12.11", readTime: "7분", color: "#e8eaf6", emoji: "✍️", featured: false },
  { id: 16, category: "트렌드", title: "AI가 바꾸는 뷰티 업계 직무 지형도", desc: "AI 도입으로 사라지는 직무 vs 새롭게 뜨는 직무 완전 분석.", date: "2024.12.08", readTime: "8분", color: "#f1f8e9", emoji: "🤖", featured: false },
  { id: 17, category: "커리어", title: "뷰티 스타트업 vs 대기업, 어디로 가야 할까?", desc: "성장 속도, 연봉, 워라밸까지. 두 선택지의 장단점을 솔직하게 비교.", date: "2024.12.05", readTime: "6분", color: "#fff8e1", emoji: "⚖️", featured: false },
  { id: 18, category: "브랜드스토리", title: "이니스프리의 변신: 제주에서 글로벌로", desc: "아모레퍼시픽의 효자 브랜드가 해외 시장에서 살아남는 방법.", date: "2024.12.02", readTime: "7분", color: "#e0f7fa", emoji: "🍃", featured: false },
];
